version: '3'

services:
  rmq0-hen: &rmq-hen
    build: rmq-hen
      # environment:
      # - LOG=debug
    hostname: rmq0-hen
  rmq1-hen:
    <<: *rmq-hen
    hostname: rmq1-hen
  rmq2-hen:
    <<: *rmq-hen
    hostname: rmq2-hen
  rmq0-web: &rmq-web
    build: rmq-web
      # environment:
      # - LOG=debug
    hostname: rmq0-web
  rmq1-web:
    <<: *rmq-web
    hostname: rmq1-web
  rmq2-web:
    <<: *rmq-web
    hostname: rmq2-web
  haproxy-hen:
    image: haproxy:latest
    volumes:
      - ./haproxy-hen.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq0-hen
      - rmq1-hen
      - rmq2-hen
    ports:
      # HOST:CONTAINER
      - 15672:15672
  haproxy-web:
    image: haproxy:latest
    volumes:
      - ./haproxy-web.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rmq0-web
      - rmq1-web
      - rmq2-web
    ports:
      # HOST:CONTAINER
      - 15673:15672
