version: '3'

services:
  rmq0-hdc: &rmq-hdc
    build: rmq-hdc
    hostname: rmq0-hdc
    ports:
      # HOST:CONTAINER
      - 15672:15672
      - 5672:5672
  rmq0-wdc: &rmq-wdc
    build: rmq-wdc
    hostname: rmq0-wdc
    ports:
      # HOST:CONTAINER
      - 15673:15672
      - 5673:5672
  rmq0-odc: &rmq-odc
    build: rmq-odc
    hostname: rmq0-odc
    ports:
      # HOST:CONTAINER
      - 15674:15672
      - 5674:5672
